# Generated by Django 3.2.13 on 2022-06-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='access_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
